name: Deploy

on:
  push:
    branches:
      - melb-2024

jobs:
  deploy:
    runs-on: ubuntu-20.04

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'checkout'
        uses: 'actions/checkout@v3'
      - id: 'setup-node'
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - id: 'build'
        run: npm run build
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }},
          service_account: 'github@dddmelbourne.iam.gserviceaccount.com'
